#ifndef PROTOCOL_H
#define PROTOCOL_H

#define CMD_USER "USER"
#define CMD_PASS "PASS"
#define CMD_REGISTER "REGISTER"
#define CMD_LIST "LIST"
#define CMD_LISTSHARED "LISTSHARED" 
#define CMD_SEARCH "SEARCH"
#define CMD_SHARE "SHARE"
#define CMD_DELETE "DELETE"
#define CMD_RENAME "RENAME"
#define CMD_UPLOAD_CHECK "SITE QUOTA_CHECK"
#define CMD_UPLOAD "STOR"
#define CMD_DOWNLOAD "RETR"
#define CMD_DOWNLOAD_FOLDER "DOWNLOAD_FOLDER"
#define CMD_GET_FOLDER_STRUCTURE "GET_FOLDER_STRUCTURE"
#define CMD_SHARE_FOLDER "SHARE_FOLDER"
#define CMD_UPLOAD_FILE "UPLOAD_FILE"
#define CMD_CHECK_SHARE_PROGRESS "CHECK_SHARE_PROGRESS"
#define CMD_CANCEL_FOLDER_SHARE "CANCEL_FOLDER_SHARE"
#define CMD_CREATE_FOLDER "CREATE_FOLDER"

#define TYPE_FILE 1
#define TYPE_DIR  2
#define TYPE_END  3

#define CODE_OK "200"
#define CODE_LOGIN_SUCCESS "230"
#define CODE_DATA_OPEN "150"
#define CODE_CHUNK_ACK "151"
#define CODE_TRANSFER_COMPLETE "226"
#define CODE_LOGIN_FAIL "530"
#define CODE_FAIL "550"

#endif